// Copyright 2023 SandboxAQ
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/api/v1/encoding_format.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ASN1EncodingFormat int32

const (
	ASN1EncodingFormat_ENCODING_FORMAT_PEM ASN1EncodingFormat = 0
	ASN1EncodingFormat_ENCODING_FORMAT_DER ASN1EncodingFormat = 1
)

// Enum value maps for ASN1EncodingFormat.
var (
	ASN1EncodingFormat_name = map[int32]string{
		0: "ENCODING_FORMAT_PEM",
		1: "ENCODING_FORMAT_DER",
	}
	ASN1EncodingFormat_value = map[string]int32{
		"ENCODING_FORMAT_PEM": 0,
		"ENCODING_FORMAT_DER": 1,
	}
)

func (x ASN1EncodingFormat) Enum() *ASN1EncodingFormat {
	p := new(ASN1EncodingFormat)
	*p = x
	return p
}

func (x ASN1EncodingFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASN1EncodingFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_encoding_format_proto_enumTypes[0].Descriptor()
}

func (ASN1EncodingFormat) Type() protoreflect.EnumType {
	return &file_proto_api_v1_encoding_format_proto_enumTypes[0]
}

func (x ASN1EncodingFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASN1EncodingFormat.Descriptor instead.
func (ASN1EncodingFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_encoding_format_proto_rawDescGZIP(), []int{0}
}

var File_proto_api_v1_encoding_format_proto protoreflect.FileDescriptor

var file_proto_api_v1_encoding_format_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x73, 0x61, 0x71, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2a,
	0x46, 0x0a, 0x12, 0x41, 0x53, 0x4e, 0x31, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49, 0x4e,
	0x47, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x50, 0x45, 0x4d, 0x10, 0x00, 0x12, 0x17,
	0x0a, 0x13, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41,
	0x54, 0x5f, 0x44, 0x45, 0x52, 0x10, 0x01, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2d, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x75, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68, 0x2f, 0x67,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_v1_encoding_format_proto_rawDescOnce sync.Once
	file_proto_api_v1_encoding_format_proto_rawDescData = file_proto_api_v1_encoding_format_proto_rawDesc
)

func file_proto_api_v1_encoding_format_proto_rawDescGZIP() []byte {
	file_proto_api_v1_encoding_format_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_encoding_format_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_v1_encoding_format_proto_rawDescData)
	})
	return file_proto_api_v1_encoding_format_proto_rawDescData
}

var file_proto_api_v1_encoding_format_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_v1_encoding_format_proto_goTypes = []interface{}{
	(ASN1EncodingFormat)(0), // 0: saq.sandwich.proto.api.v1.ASN1EncodingFormat
}
var file_proto_api_v1_encoding_format_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_v1_encoding_format_proto_init() }
func file_proto_api_v1_encoding_format_proto_init() {
	if File_proto_api_v1_encoding_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_v1_encoding_format_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_v1_encoding_format_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_encoding_format_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_encoding_format_proto_enumTypes,
	}.Build()
	File_proto_api_v1_encoding_format_proto = out.File
	file_proto_api_v1_encoding_format_proto_rawDesc = nil
	file_proto_api_v1_encoding_format_proto_goTypes = nil
	file_proto_api_v1_encoding_format_proto_depIdxs = nil
}
