// Copyright 2023 SandboxAQ
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/api/v1/verifiers.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyVerifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyVerifier) Reset() {
	*x = EmptyVerifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_verifiers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyVerifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyVerifier) ProtoMessage() {}

func (x *EmptyVerifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_verifiers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyVerifier.ProtoReflect.Descriptor instead.
func (*EmptyVerifier) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_verifiers_proto_rawDescGZIP(), []int{0}
}

type X509Verifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustedCas              []*Certificate `protobuf:"bytes,1,rep,name=trusted_cas,json=trustedCas,proto3" json:"trusted_cas,omitempty"`
	VerifyCertificateSpki   [][]byte       `protobuf:"bytes,2,rep,name=verify_certificate_spki,json=verifyCertificateSpki,proto3" json:"verify_certificate_spki,omitempty"`
	VerifyCertificateHash   [][]byte       `protobuf:"bytes,3,rep,name=verify_certificate_hash,json=verifyCertificateHash,proto3" json:"verify_certificate_hash,omitempty"`
	AllowExpiredCertificate bool           `protobuf:"varint,4,opt,name=allow_expired_certificate,json=allowExpiredCertificate,proto3" json:"allow_expired_certificate,omitempty"`
	MaxVerifyDepth          uint32         `protobuf:"varint,5,opt,name=max_verify_depth,json=maxVerifyDepth,proto3" json:"max_verify_depth,omitempty"`
}

func (x *X509Verifier) Reset() {
	*x = X509Verifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_verifiers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509Verifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509Verifier) ProtoMessage() {}

func (x *X509Verifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_verifiers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509Verifier.ProtoReflect.Descriptor instead.
func (*X509Verifier) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_verifiers_proto_rawDescGZIP(), []int{1}
}

func (x *X509Verifier) GetTrustedCas() []*Certificate {
	if x != nil {
		return x.TrustedCas
	}
	return nil
}

func (x *X509Verifier) GetVerifyCertificateSpki() [][]byte {
	if x != nil {
		return x.VerifyCertificateSpki
	}
	return nil
}

func (x *X509Verifier) GetVerifyCertificateHash() [][]byte {
	if x != nil {
		return x.VerifyCertificateHash
	}
	return nil
}

func (x *X509Verifier) GetAllowExpiredCertificate() bool {
	if x != nil {
		return x.AllowExpiredCertificate
	}
	return false
}

func (x *X509Verifier) GetMaxVerifyDepth() uint32 {
	if x != nil {
		return x.MaxVerifyDepth
	}
	return 0
}

var File_proto_api_v1_verifiers_proto protoreflect.FileDescriptor

var file_proto_api_v1_verifiers_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x73, 0x61, 0x71, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xad, 0x02, 0x0a, 0x0c, 0x58,
	0x35, 0x30, 0x39, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0b, 0x74,
	0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x73, 0x61, 0x71, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65,
	0x64, 0x43, 0x61, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x70, 0x6b, 0x69, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x15, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x70, 0x6b, 0x69, 0x12, 0x36, 0x0a, 0x17,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x15, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x3a, 0x0a, 0x19, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x64,
	0x65, 0x70, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x65, 0x70, 0x74, 0x68, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63,
	0x68, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x63, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_api_v1_verifiers_proto_rawDescOnce sync.Once
	file_proto_api_v1_verifiers_proto_rawDescData = file_proto_api_v1_verifiers_proto_rawDesc
)

func file_proto_api_v1_verifiers_proto_rawDescGZIP() []byte {
	file_proto_api_v1_verifiers_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_verifiers_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_v1_verifiers_proto_rawDescData)
	})
	return file_proto_api_v1_verifiers_proto_rawDescData
}

var file_proto_api_v1_verifiers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_v1_verifiers_proto_goTypes = []interface{}{
	(*EmptyVerifier)(nil), // 0: saq.sandwich.proto.api.v1.EmptyVerifier
	(*X509Verifier)(nil),  // 1: saq.sandwich.proto.api.v1.X509Verifier
	(*Certificate)(nil),   // 2: saq.sandwich.proto.api.v1.Certificate
}
var file_proto_api_v1_verifiers_proto_depIdxs = []int32{
	2, // 0: saq.sandwich.proto.api.v1.X509Verifier.trusted_cas:type_name -> saq.sandwich.proto.api.v1.Certificate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_v1_verifiers_proto_init() }
func file_proto_api_v1_verifiers_proto_init() {
	if File_proto_api_v1_verifiers_proto != nil {
		return
	}
	file_proto_api_v1_certificate_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_api_v1_verifiers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyVerifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_verifiers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509Verifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_v1_verifiers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_v1_verifiers_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_verifiers_proto_depIdxs,
		MessageInfos:      file_proto_api_v1_verifiers_proto_msgTypes,
	}.Build()
	File_proto_api_v1_verifiers_proto = out.File
	file_proto_api_v1_verifiers_proto_rawDesc = nil
	file_proto_api_v1_verifiers_proto_goTypes = nil
	file_proto_api_v1_verifiers_proto_depIdxs = nil
}
