///
/// \file
/// \brief Enum IOError in namespace saq::sandwich::io.
///
/// \warning AUTOGENERATED -- DO NOT EDIT */

#pragma once

namespace saq::sandwich::io {

/// \brief Enum IOError.
enum class IOError : int { 
  kOk = 0,
  kInProgress = 1,
  kWouldBlock = 2,
  kRefused = 3,
  kClosed = 4,
  kInvalid = 5,
  kUnknown = 6,
};

} // end namespace saq::sandwich::io
