version: 2.1

jobs:
  run-all-tests:
    docker:
      - image: "us-docker.pkg.dev/pqc-infra-test/circleci-runner/runner:latest"
        auth:
          username: _json_key
          password: $RUNNER_GCR_SA_KEY
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: "Run all test targets"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}
            bazelisk --bazelrc .circleci/cache.bazelrc test --config=cicd //...
      - run:
          name: "Test the external Go & Python integrations"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}
            bazelisk build --config=cicd --remote_cache=https://storage.googleapis.com/bazel-cache-bucket-3100644879 \
              --google_default_credentials \
              sandwich_c/...
            export CC=clang-13
            export CXX=clang++-13

            export CGO_CFLAGS="-I$PWD -I$PWD/bazel-bin/"
            export CGO_LDFLAGS="-L$PWD/bazel-bin/rust/"
            export GO_EXAMPLE_DIR="$PWD/examples/go/echo_tls_server"
            echo "replace github.com/sandbox-quantum/sandwich/go => $PWD/go" >>"$GO_EXAMPLE_DIR/go.mod"
            pushd "$GO_EXAMPLE_DIR" && go build && popd

            python3 -m venv venv
            source venv/bin/activate
            pip install .
            SANDWICH_C_LIB="$PWD/bazel-bin/rust/libsandwich_full.so" python -c 'from pysandwich import sandwich; sandwich.sandwich()'
      - run:
          name: "Build the Rust package natively"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}

            export CARGO_BAZELISK_EXTRA_ARGS="--config=cicd --remote_cache=https://storage.googleapis.com/bazel-cache-bucket-3100644879 --google_default_credentials"
            export CC=clang-13
            export CXX=clang++-13

            cargo build --release -vv
            cargo test --release --lib -vv

  release-linux-dockerbuild:
    parameters:
      mode:
        description: "Build release mode"
        type: enum
        enum:
          - debug
          - release
        default: release
      arch:
        description: "Build machine architecture"
        type: enum
        enum:
          - arm.xlarge
          - xlarge
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: << parameters.arch >>
    steps:
      - checkout
      - run:
          name: "Compile through docker"
          command: |
            if [[ "<< parameters.mode >>" -eq "release" ]]; then
              bazelArgs=(--build-arg bazelArgs='-c opt')
            fi
            docker build . -t="sandwich" -f Dockerfile.linux "${bazelArgs[@]}"

            # TODO: Update docker vesion, the one provided does not support `--output`
            docker cp $(docker create --name sw sandwich sleep 100):/export.tar.bz2 export.tar.bz2 && docker rm sw
      - run:
          name: "Rename export"
          command: |
            finalName=sandwich_<< parameters.mode >>_$(dpkg --print-architecture)
            mkdir -p ~/export_artifacts
            mv export.tar.bz2  ~/export_artifacts/${finalName}.tar.bz2
      - store_artifacts:
          name: "Export build artifacts"
          path: ~/export_artifacts/

  release-macos:
    macos:
      xcode: 14.0.0
    resource_class: << parameters.resource >>
    parameters:
      resource:
        description: "Resource class"
        type: enum
        enum:
          - macos.m1.large.gen1
          - macos.x86.medium.gen2
      platform:
        description: "Target platform"
        type: enum
        enum:
          - macos_x86_64
          - macos_aarch64
      artifact_file_name:
        description: "Artifact file name"
        type: string
    steps:
      - checkout
      - run:
          name: "Install bazelisk"
          command: |
            curl -L --output /usr/local/bin/bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-darwin-arm64"
            chmod +x /usr/local/bin/bazelisk
      - run:
          name: "Build release"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}

            # Not sourced by default on macOS executor
            if [[ -f "${BASH_ENV}" ]]; then
              source "${BASH_ENV}"
            fi

            export PLATFORM_FLAG="--platforms=//common/platforms:<< parameters.platform >>"

            bazelisk build //:export \
              -c opt \
              "${PLATFORM_FLAG}" \
              --remote_cache=https://storage.googleapis.com/bazel-cache-bucket-3100644879 \
              --google_default_credentials \
              --profile=/tmp/bazel-profile-<< parameters.resource >>.gz \

            mkdir -p ~/export_artifacts
            mv "$(bazelisk cquery -c opt "${PLATFORM_FLAG}" --output=files //:export)" ~/export_artifacts/<< parameters.artifact_file_name >>

      - store_artifacts:
          name: "Export build artifacts"
          path: ~/export_artifacts/

  publish-doc:
    docker:
      - image: "us-docker.pkg.dev/pqc-infra-test/circleci-runner/runner:latest"
        auth:
          username: _json_key
          password: $RUNNER_GCR_SA_KEY
    resource_class: xlarge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cb:67:a0:71:3b:89:1b:19:d6:40:d5:b8:84:38:33:a4"
      - run:
          name: "Deploy documentation"
          command: |
            DOC_HTML=$(bazelisk cquery --output files //docs:docs)
            bazelisk build //docs:docs
            ghp-import "$DOC_HTML" -p -o


  push-to-oss:
    docker:
      - image: "us-docker.pkg.dev/pqc-infra-test/circleci-runner/runner:latest"
        auth:
          username: _json_key
          password: $RUNNER_GCR_SA_KEY
    resource_class: xlarge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cb:67:a0:71:3b:89:1b:19:d6:40:d5:b8:84:38:33:a4"
      - run:
          name: "Run copybara"
          command: |
            git config --global user.email "invalid@circleci.com"
            git config --global user.name "CircleCI Presubmit"
            git config --global init.defaultBranch main
            COPYBARA_EXIT=0
            copybara .circleci/copy.bara.sky push \
              || COPYBARA_EXIT=$?
            # Exit code of 4 means "nothing to do" and should be accepted.
            # See https://github.com/google/copybara/blob/2afcc6413be20ba2ea2732e04b2b32e039631ade/java/com/google/copybara/util/ExitCode.java#L42
            if [ $COPYBARA_EXIT -ne 0 -a $COPYBARA_EXIT -ne 4 ]; then
              echo Copybara failed.
              exit 1
            fi

workflows:
  presubmit:
    jobs:
      - run-all-tests:
          context:
            - bazel-cache
      - release-linux-dockerbuild:
          name: release-linux-dockerbuild_amd64
          mode: release
          arch: xlarge
      - release-linux-dockerbuild:
          name: release-linux-dockerbuild_arm64
          mode: release
          arch: arm.xlarge
      - release-macos:
          context:
            - bazel-cache
          name: release-macos-aarch64
          resource: macos.m1.large.gen1
          platform: macos_aarch64
          artifact_file_name: "sandwich-macos-arm64.tar.bz2"
      - release-macos:
          context:
            - bazel-cache
          name: release-macos-x86_64
          resource: macos.m1.large.gen1
          platform: macos_x86_64
          artifact_file_name: "sandwich-macos-x86_64.tar.bz2"
      - publish-doc:
          context:
            - bazel-cache
          requires:
            - run-all-tests
      - push-to-oss:
          context:
            - bazel-cache
          requires:
            - run-all-tests
          filters:
            branches:
              only:
                - main
