version: 2.1

jobs:
  run-all-tests:
    resource_class: xlarge
    docker:
      - image: "us-docker.pkg.dev/pqc-infra-test/circleci-runner/runner:latest"
        auth:
          username: _json_key
          password: $RUNNER_GCR_SA_KEY
    steps:
      - checkout
      - run:
          name: "Run all test targets"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}
            bazelisk test --remote_cache=https://storage.googleapis.com/bazel-cache-bucket-3100644879 \
              --google_default_credentials \
              //...
      - run:
          name: "Test the external Go & Python integrations"
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
            echo ${BAZEL_CACHE_GCS_SA_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}
            bazelisk build --remote_cache=https://storage.googleapis.com/bazel-cache-bucket-3100644879 \
              --google_default_credentials \
              sandwich_c/...
            export CC=clang-13
            export CXX=clang++-13

            export CGO_CFLAGS="-I$PWD -I$PWD/bazel-bin/"
            export CGO_LDFLAGS="-L$PWD/bazel-bin/rust/"
            export GO_EXAMPLE_DIR="$PWD/examples/go/echo_tls_server"
            echo "replace github.com/sandbox-quantum/sandwich/go => $PWD/go" >>"$GO_EXAMPLE_DIR/go.mod"
            pushd "$GO_EXAMPLE_DIR" && go build && popd

            sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yyq python3-{pip,venv}
            python3 -m venv venv
            source venv/bin/activate
            pip install .
            SANDWICH_C_LIB="$PWD/bazel-bin/rust/libsandwich_full.so" python -c 'from pysandwich import sandwich; sandwich.Sandwich()'

  publish-doc:
    resource_class: xlarge
    docker:
      - image: "us-docker.pkg.dev/pqc-infra-test/circleci-runner/runner:latest"
        auth:
          username: _json_key
          password: $RUNNER_GCR_SA_KEY
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cb:67:a0:71:3b:89:1b:19:d6:40:d5:b8:84:38:33:a4"
      - run:
          name: "Deploy documentation"
          command: |
            DOC_HTML=$(bazelisk cquery --output files //docs:docs)
            bazelisk build //docs:docs
            ghp-import "$DOC_HTML" -p -o

workflows:
  presubmit:
    jobs:
      - run-all-tests:
          context:
            - bazel-cache
      - publish-doc:
          filters:
            branches:
              only:
                - main
