///
/// \file
/// \brief Enum State in namespace saq::sandwich::tunnel.
///
/// \warning AUTOGENERATED -- DO NOT EDIT */

#pragma once

namespace saq::sandwich::tunnel {

/// \brief Enum State.
enum class State : int { 
  kNotConnected = 0,
  kConnectionInProgress = 1,
  kHandshakeInProgress = 2,
  kHandshakeDone = 3,
  kBeingShutdown = 4,
  kDisconnected = 5,
  kError = 6,
};

} // end namespace saq::sandwich::tunnel
