///
/// \file
/// \brief Enum HandshakeState in namespace saq::sandwich::tunnel.
///
/// \warning AUTOGENERATED -- DO NOT EDIT */

#pragma once

namespace saq::sandwich::tunnel {

/// \brief Enum HandshakeState.
enum class HandshakeState : int { 
  kInProgress = 0,
  kDone = 1,
  kWantRead = 2,
  kWantWrite = 3,
  kError = 4,
};

} // end namespace saq::sandwich::tunnel
