///
/// \file
/// \brief Enum RecordError in namespace saq::sandwich::tunnel.
///
/// \warning AUTOGENERATED -- DO NOT EDIT */

#pragma once

namespace saq::sandwich::tunnel {

/// \brief Enum RecordError.
enum class RecordError : int { 
  kOk = 0,
  kWantRead = 1,
  kWantWrite = 2,
  kBeingShutdown = 3,
  kClosed = 4,
  kUnknown = 5,
};

} // end namespace saq::sandwich::tunnel
