// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/api/v1/private_key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//	*PrivateKey_Static
	Source isPrivateKey_Source `protobuf_oneof:"source"`
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescGZIP(), []int{0}
}

func (m *PrivateKey) GetSource() isPrivateKey_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *PrivateKey) GetStatic() *ASN1DataSource {
	if x, ok := x.GetSource().(*PrivateKey_Static); ok {
		return x.Static
	}
	return nil
}

type isPrivateKey_Source interface {
	isPrivateKey_Source()
}

type PrivateKey_Static struct {
	Static *ASN1DataSource `protobuf:"bytes,1,opt,name=static,proto3,oneof"`
}

func (*PrivateKey_Static) isPrivateKey_Source() {}

var File_saq_pqc_sandwich_proto_api_v1_private_key_proto protoreflect.FileDescriptor

var file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x73, 0x61, 0x71, 0x2f, 0x70, 0x71, 0x63, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x63, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1d, 0x73, 0x61, 0x71, 0x2e, 0x70, 0x71, 0x63, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x1a, 0x2f, 0x73, 0x61, 0x71, 0x2f, 0x70, 0x71, 0x63, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x63, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5f, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x47, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x73, 0x61, 0x71, 0x2e, 0x70, 0x71, 0x63, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x53, 0x4e, 0x31, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d,
	0x2f, 0x63, 0x68, 0x75, 0x6e, 0x67, 0x75, 0x73, 0x2f, 0x73, 0x61, 0x71, 0x2f, 0x70, 0x71, 0x63,
	0x2f, 0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x63, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescOnce sync.Once
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescData = file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDesc
)

func file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescGZIP() []byte {
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescOnce.Do(func() {
		file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescData)
	})
	return file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDescData
}

var file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_saq_pqc_sandwich_proto_api_v1_private_key_proto_goTypes = []interface{}{
	(*PrivateKey)(nil),     // 0: saq.sandwich.proto.api.v1.PrivateKey
	(*ASN1DataSource)(nil), // 1: saq.sandwich.proto.api.v1.ASN1DataSource
}
var file_saq_pqc_sandwich_proto_api_v1_private_key_proto_depIdxs = []int32{
	1, // 0: saq.sandwich.proto.api.v1.PrivateKey.static:type_name -> saq.sandwich.proto.api.v1.ASN1DataSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_saq_pqc_sandwich_proto_api_v1_private_key_proto_init() }
func file_saq_pqc_sandwich_proto_api_v1_private_key_proto_init() {
	if File_saq_pqc_sandwich_proto_api_v1_private_key_proto != nil {
		return
	}
	file_saq_pqc_sandwich_proto_api_v1_data_source_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PrivateKey_Static)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saq_pqc_sandwich_proto_api_v1_private_key_proto_goTypes,
		DependencyIndexes: file_saq_pqc_sandwich_proto_api_v1_private_key_proto_depIdxs,
		MessageInfos:      file_saq_pqc_sandwich_proto_api_v1_private_key_proto_msgTypes,
	}.Build()
	File_saq_pqc_sandwich_proto_api_v1_private_key_proto = out.File
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_rawDesc = nil
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_goTypes = nil
	file_saq_pqc_sandwich_proto_api_v1_private_key_proto_depIdxs = nil
}
